CREATE TABLE item_price_info ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
                                조사일자 DATE ,
                                조사구분코드 SMALLINT ,
                                조사구분명 VARCHAR(50),
                                표준품목코드 MEDIUMINT,
                                표준품목명   VARCHAR(25),
                                조사가격품목코드 SMALLINT,
                                조사가격품목명 VARCHAR(25),
                                표준품종코드 MEDIUMINT,
                                표준품종명 VARCHAR(40),
                                조사가격품종코드 SMALLINT,
                                조사가격품종명 VARCHAR(40),
                                조사등급코드 SMALLINT,
                                조사등급명 VARCHAR(20),
                                표준단위코드 VARCHAR(0),
                                표준단위명 VARCHAR(0),
                                조사단위명 VARCHAR(20),
                                당일조사가격   INT,
                                전일조사가격   INT,
                                조사지역코드  SMALLINT,
                                조사지역명 VARCHAR(20),
                                표준시장코드 INT,
                                표준시장명 VARCHAR(50),
                                조사가격시장코드 SMALLINT,
                                조사가격시장명 VARCHAR(40) )