public_price = {
    "조사일자": "object",
    "조사구분코드": "UInt8",
    "조사구분명": "object",
    "표준품목코드": "UInt16",
    "표준품목명": "object",
    "조사가격품목코드": "UInt16",
    "조사가격품목명": "object",
    "표준품종코드": "object",
    "표준품종명": "object",
    "조사가격품종코드": "UInt8",
    "조사가격품종명": "object",
    "조사등급코드": "UInt8",
    "조사등급명": "object",
    "표준단위코드": "UInt8",
    "표준단위명": "object",
    "조사단위명": "object",
    "당일조사가격": "UInt32",
    "전일조사가격": "UInt32",
    "조사지역코드": "UInt16",
    "조사지역명": "object",
    "표준시장코드": "UInt32",
    "표준시장명": "object",
    "조사가격시장코드": "UInt8",
    "조사가격시장명": "object"
}
