dtype = {
    "public_price": {
        "조사일자": "object",
        "조사구분코드": "UInt8",
        "조사구분명": "object",
        "표준품목코드": "UInt16",
        "표준품목명": "object",
        "조사가격품목코드": "UInt16",
        "조사가격품목명": "object",
        "표준품종코드": "object",
        "표준품종명": "object",
        "조사가격품종코드": "UInt8",
        "조사가격품종명": "object",
        "조사등급코드": "UInt8",
        "조사등급명": "object",
        "표준단위코드": "UInt8",
        "표준단위명": "object",
        "조사단위명": "object",
        "당일조사가격": "UInt32",
        "전일조사가격": "UInt32",
        "조사지역코드": "UInt16",
        "조사지역명": "object",
        "표준시장코드": "UInt32",
        "표준시장명": "object",
        "조사가격시장코드": "UInt8",
        "조사가격시장명": "object"
    },

    # TODO: find proper type for each attributes.
    "public_terrestrial_weather": {
        "지점": "object",
        "지점명": "object",
        "일시": "object",
        "평균기온(°C)": "object",
        "최저기온(°C)": "object",
        "최고기온(°C)": "object",
        "강수 계속시간(hr)": "object",
        "일강수량(mm)": "object",
        "최대 풍속(m/s)": "object",
        "평균 풍속(m/s)": "object",
        "최소 상대습도(%)": "object",
        "평균 상대습도(%)": "object",
        "합계 일조시간(hr)": "object",
        "합계 일사량(MJ/m2)": "object"
    },

    "public_marine_weather": {
        "지점": "",
        "일시": "object",
        "평균 풍속(m/s)": "",
        "평균기압(hPa)": "",
        "평균 상대습도(%)": "",
        "평균 기온(°C)": "",
        "평균 수온(°C)": "",
        "평균 최대 파고(m)": "",
        "평균 유의 파고(m)": "",
        "최고 유의 파고(m)": "",
        "최고 최대 파고(m)": "",
        "평균 파주기(sec)": "",
        "최고 파주기(sec)": "",
    }
}
