CREATE TABLE IF NOT EXISTS user_item( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
        user_id INT NOT NULL ,
        item_id INT NOT NULL  ,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE ,
        FOREIGN KEY (item_id) REFERENCES item(id) ON UPDATE CASCADE ON DELETE CASCADE )