CREATE TABLE IF NOT EXISTS season ( id INT NOT NULL  AUTO_INCREMENT PRIMARY KEY ,
        season_name VARCHAR(20) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)