CREATE TABLE IF NOT EXISTS item_frequency (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        item_id INT NOT NULL ,
        item_frequency NUMERIC(2,1) NOT NULL ,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (item_id) REFERENCES item(id) ON UPDATE CASCADE ON DELETE CASCADE )