CREATE TABLE IF NOT EXISTS user( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        gender TINYINT(2) ,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)