INSERT INTO recipe (name , season_id , maker ) VALUES
("김치찌개" ,null ,""),
("팥죽" , 4,"") ,
("삼계탕" , 2,""),
("초기매운탕", null,""),
("황태국" , null,""),
("진미채", null,""),
("고등어조림",null,""),
("잡채",null,""),
("토마토파스타",null,""),
("알리오올리오파스타",null,""),
("골뱅이무침",null,""),
("두부조림",null,""),
("숙주나물무침",null,""),
("순두부찌개",null,""),
("소고기숙주볶음",null,"")
